### ISSUE TITLE
minimum height should be allowed

### ISSUE THREAD

**Issue by simmerz** [stimulus-components/stimulus-textarea-autogrow#2]
When implementing this on an empty textarea, it shrinks right down to less than one line. This feels like poor UX, and the element has a `rows` attribute set:

<img width="502" alt="Screenshot 2021-08-11 at 08 34 45" src="https://user-images.githubusercontent.com/24327/128988703-058228dc-ddf3-472f-a45c-3c0a8b4262a0.png">

Proposal:
Use the `rows` attribute to determine minimum height. Perhaps that can then be set as a px value once connected and autogrow could check that value against the current `scrollHeight`

**Comment by guillaumebriday** [comment]
Hum, I don't reproduce this bug with the demo when the textarea is empty. It's always at least a line (in Chrome) or a bit more in Safari and Firefox.

Do you have more info or can you reproduce that in the demo too?

**Comment by artur79** [comment]
@simmerz check my fix here, maybe it would help too https://github.com/stimulus-components/stimulus-textarea-autogrow/issues/5
but actually I never experienced problems with empty textarea despite I also add textareas dynamically with other stimulus controller
