### ISSUE TITLE
when you start typing it drags your screen down

### ISSUE THREAD

**Issue by yshmarov** [stimulus-components/stimulus-textarea-autogrow#3]
when text is input field is longer than screen width, and you try to type anything, **it jumps your screen down.** 
this renders the stimulus-textarea-autogrow unusable in any real scenario :(

example 1:
![textarea autogrow bug 2](https://user-images.githubusercontent.com/13472945/131323010-0baecb3a-f92e-451e-becd-5e7e89360ca3.gif)

example 2:
![textarea autogrow bug](https://user-images.githubusercontent.com/13472945/131322730-1d79fd28-17dd-43c4-8bde-f8163b5e515a.gif)

**Comment by guillaumebriday** [comment]
Well I manage to reproduce that bug too.

I think it's a bug because we are updating the textarea height. I don't know how to fix that yet, do you have an idea?

**Comment by yshmarov** [comment]
Gotta think about it;
Not stimulus, but will leave it here for later: https://css-tricks.com/the-cleanest-trick-for-autogrowing-textareas/

**Comment by ocarreterom** [comment]
I'm currently using a Stimulus controller wrapper with https://github.com/jackmoore/autosize and works fine.

**Comment by lb-** [comment]
I think this is the code that handles this in the jQuery UI one. 

https://github.com/jackmoore/autosize/blob/master/src/autosize.js#L86

**Comment by guillaumebriday** [comment]
Sorry for my late reply,

To be honest, I didn't know this project: https://github.com/jackmoore/autosize but it seems to be perfect and maybe doing a wrapper around it is the best idea 👍 

We should do that for the v5.x
