### ISSUE TITLE
Expecting for @hotwired/stimulus version 3

### ISSUE THREAD

**Issue by charlietag** [stimulus-components/stimulus-textarea-autogrow#4]
I love using this components concept.
May I ask is there any plans for upgrading to @hotwired/stimulus version 3?

Thanks

**Comment by guillaumebriday** [comment]
Yep, I already did few of other components from the library and I will continue in the next days, weeks to upgrade them all.

**Comment by guillaumebriday** [comment]
Feel free to open PRs to help me ;)

**Comment by hardanders-dev** [comment]
I just opened a pull request addressing this :-)  #7

**Comment by guillaumebriday** [comment]
Done and released

thanks @hardanders-dev
