### ISSUE TITLE
maximum height should be allowed

### ISSUE THREAD

**Issue by axzx** [stimulus-components/stimulus-textarea-autogrow#6]
You can set the maximum height in the configuration.
When the user types so much text that the textarea grows to its maximum level, a scroll will appear.

**Comment by lb-** [comment]
The jQuery UI text area resize handling of this using the style attribute could be a reasonable way to go. 

http://www.jacklmoore.com/autosize/#faq-min-max

**Comment by guillaumebriday** [comment]
Thanks @lb- it works fine
