### ISSUE TITLE
4.1.0 is still missing in jspm.io CDN

### ISSUE THREAD

**Issue by hachi8833** [stimulus-components/stimulus-textarea-autogrow#8]
Could you make 4.1.0 available on jspm.io?

* NG: https://ga.jspm.io/npm:stimulus-scroll-to@4.1.0/dist/stimulus-textarea-autogrow.es.js
* OK: https://ga.jspm.io/npm:stimulus-scroll-to@4.0.0/dist/stimulus-textarea-autogrow.es.js

**Comment by guillaumebriday** [comment]
Similar to https://github.com/stimulus-components/stimulus-scroll-to/issues/3#issuecomment-1533252544
